#!/usr/bin/env ruby
# frozen_string_literal: true

module CovLoupeExecutable
  MINIMUM_RUBY_VERSION = '3.2'
  SIGNAL_EXIT_BASE = 128

  def self.run
    install_signal_handlers
    handle_executable_flags
    ensure_ruby_version!
    run_application
  end

  def self.install_signal_handlers
    %w[INT TERM].each do |sig|
      Signal.trap(sig) do
        $stderr.write "\nReceived SIG#{sig}. Exiting.\n"
        exit(SIGNAL_EXIT_BASE + Signal.list[sig])
      end
    end
  end

  def self.ensure_ruby_version!(minimum: MINIMUM_RUBY_VERSION)
    return unless defined?(Gem::Version)

    return if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new(minimum)

    $stderr.puts "#{File.basename($PROGRAM_NAME)} requires Ruby >= #{minimum} (current: #{RUBY_VERSION})."
    $stderr.puts 'Please run with a supported Ruby version (e.g., via rbenv, rvm, asdf, mise, rv).'
    exit 1
  end

  def self.handle_executable_flags(argv = ARGV)
    return unless argv.any? { |arg| %w[-v --version].include?(arg) }

    require_relative '../lib/cov_loupe/version'
    puts CovLoupe::VERSION
    exit 0
  end

  def self.run_application
    root = File.expand_path('..', File.realpath(__FILE__))
    lib  = File.join(root, 'lib')
    $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

    require 'cov_loupe'
    CovLoupe.run(ARGV)
  end
end

CovLoupeExecutable.run
